name: PrivatChat
main: de.gwarband.privatchat.PrivatChat
version: 0.2
author: GWarBand
description: Make a chat
commands:
   PChat:
     description: make a chat with a player
     usage: /<command> <player>
   ChatExit:
     description: exit the chat
     usage: /<command>
   BM:
     description: send a global message
     usage: /<command> <message>