name: PrivatChat
main: de.gwarband.privatchat.PrivatChat
version: 0.1
author: GWarBand
description: Make a chat
commands:
   PChat:
     description: make a chat with a player
     usage: /<command> <player>
   ChatExit:
     description: exit the chat
     usage: /<command>